### PR TITLE
Bumped version number to 3.4.0.

### PR DESCRIPTION
**Pull request by dlabrecq**
@dtaylor113 @jeff-phillips-18 please review.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
I thought library/components was not going to be checked in?

**Comment by dlabrecq** [comment]
We're no longer updating content on the old site, but it's still running until mid-June. We want the latest color updates and I didn't want to leave this build broken. This will likely be the last update until we hard release the new site.

**Comment by dlabrecq** [comment]
Sorry, I just realized you're referring to the components directory. The patternfly-site repo is for the existing, older site. It does not use Jenkins and runs Wordpress. Therefore, library/components must be checked in. It's not check-in for the patternfly-org repo (i.e., the new site) because we use Jenkins there to build.

**Comment by jeff-phillips-18** [comment]
Ah, OK. LGTM then.

**Comment by dtaylor113** [comment]
LGTM

**Pull request merged**
